[workspace]
members = [
    "crates/broker",
    "crates/core",
    "crates/ui",
    "crates/policy",
    "crates/audit",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0"
publish = false

[workspace.lints.rust]
unsafe_code = "forbid"

