[package]
name = "saf-ui"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"

[lib]
path = "src/lib.rs"

[dependencies]
tauri = { version = "2.0", features = [], optional = true }
serde = { version = "1.0", features = ["derive"] }
