// This crate builds a WebAssembly component exporting the `app` world as defined in
// crates/wit/world.wit. It implements a minimal `start()` function for demo.

// The `bindings` module is generated by cargo-component at build time.

mod bindings;
use bindings::Guest;

struct Component;

impl Guest for Component {
    fn start() -> String {
        "hello from saf-component-demo".to_string()
    }
}

bindings::__export_world_app_cabi!(Component with_types_in bindings);
